### ISSUE TITLE
Some help needed [newby alert]

### ISSUE THREAD

**Issue by jl2035** [mikebryant/django-jquery-lightbox#1]
Can I get some help here? I don't know how one would use this. I installed using pip:

```
pip install django-jquery-lightbox
```

so what do I have to do now? Add it to INSTALLED_APPS in my project? I can't find any documentation on how to use these kind of packages.

**Comment by mikebryant** [comment]
The intended usage is:
- Add `django-jquery-lightbox` to your `install_requires`
- Add `jquery_lightbox` to your `INSTALLED_APPS`
- Reference `{% static 'js/lightbox.js' %}` in your templates - or similar for css etc.

**Comment by jl2035** [comment]
Ok it works, I just did not understand what you mean with adding to install_requires? Where is that?

**Comment by mikebryant** [comment]
It's an argument to setup.py: https://pythonhosted.org/setuptools/setuptools.html#declaring-dependencies

When you install your package with pip etc, it'll automatically pull down all the dependencies needed for your package.

**Comment by jl2035** [comment]
Strange, but I cannot find setup.py anywhere..

**Comment by mikebryant** [comment]
You might want to read up here:
https://packaging.python.org/en/latest/distributing.html

**Comment by jl2035** [comment]
Well, I don't think I need that. I only have a django website and I don't plan to release it like a package.

Thanks for clearing this up. Why not add your instructions to the readme file..?

**Comment by mikebryant** [comment]
Even for our internal only packages we use setup.py - it lets someone new to the project just run 'pip install -e .' and get all of the dependencies pulled down.
I've just ended up doing it for everything. When I deploy something it means all the dependencies just appear, no need to manually install them etc.

Mostly I just needed this packaged so other projects could depend on it, didn't spend any time on it.
